language: android
    
android:
  components:
    - build-tools-26
    - build-tools-27.0.3
    - android-26
    - android-27
    - extra
    
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install: 
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew

branches:
  only:
  - master

# Override the install and test so that we don't run integration tests
install:
  - ./gradlew assemble

script:
  - ./gradlew :facebook:test -i
  - ./gradlew uploadArchives -p facebook-core
  

env:
  global:
  - secure: CZI7dwpbk3rKrwgUJIQyoyh+ELFSfcLSg9qZEZh2HybSt+GbMKW2xXjqHLlkkBANIMZpcGKPxSoA9qCp9JLSwDHdB2fR6l5ZeOWa32e0Q7Wvg0AXG7wJEDR/pxVhorJYanCZ35hM0AnlVT53BMjKtlsCjtd85ccfsMARMrpj2+i8/oKXJYFzG1Jc6O2nW672VlD/P+JEVZ32Ph78iwR23lLH0ghkCbXFoZ/z0Dp9eR7Sm60ZPxW/Wds/TR9MS4JMawKFSLjck4KiD7FY7NZ0GoLF/mcPs1qFPEPk1DVHRzA8EhFXXCYdtuYVuPaSWmg/8bdaLjDil6xPHqHFNzx6CGEWrFrVm1wzVcqdZkBRRF6xrSXgvgIJZ0ZLEtlSqc1kZ1RzJUU+x87ha9ZzR3X5pJR8KCduKlv24/OCZojwMI+MJnRcQhZj5LbJ2sf5zvQNCBja7xjY4W8oTUq9BEzeZW/xq6zXlG8iTVTbpX82pcSYc2YjdgrpLP1H+IZLu95wuGBuqkQ90o8dNjv1oALMgSqYcyPCGHoiR6Dc29CDOlUZ79TbKevdLWJgMTT0vQImfjmPGTxtONx+68pssyQkl0//T6WNKUpUe3QL5RbLKQX1+zx7VoTpa42UzFkaC+/N+soyfYNAocrFzBaGEyiOIG+CtAgpmj7zM2hEj4sezU0=
  - secure: FouKJlU57flU37ebNoPycvex5+68omA8xafolWDkgv7j0NDvJrF4S2cOSQISNWF7Au3yx+DedFZ/+5e53ysu5LubwGWN1cGI3z08mimGO7zPpDX6UZVfvVy1r6WO34tfRzufzaICIVNYrwFNG4bT9fu/RhqVVwsUzu5m8TyPox/Re3Bu49S3U6iJhn7/8rhBAkZprDa05U/W0fquDxFFCcjbHI949ng3Vfmhc+e9k6N3TdUJQ4sC6dnh6k6uKU8Ba7//oG147zJpZkzg39MauIJGDnki3r+dR0cXbCdqUq6ROPbYp3hx5qakd6M9kHbji0VV24XlVinUlG8H9RwkY9efFaJXd1tnzdZ9KnCcemtMDCxzfn3HKH580bM2EpeI8+ZCh6PN8LnFxqmLS8tA1aEAvcBsfhPMOWxOEtd3VTcx+dVp53anK0LbI6OHXrQF5ycG3DKnL52VhhLLS+6yqdqHMqcEmuWN//XZDhBcZIy1YBfERVvmNlLnJqtXrECEgT64L3U4QtoaTv0N6sc1STeIFtvP2eq7vaf0JwiDklhkzZDlJqK2YqUp0rUPmaH5lRhtbuyMDFfRq2If79unvcI7R69Fv75qhNEZLytW+IOSELCD6jInuvDSbYxSEEwY4Hbm2biubjpg0SSY3V6oP4lCEoWI87jU7z/P7M9xQ/A=

